sudo: false
language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
env:
  matrix:
   - DJANGO="Django<1.7"
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
install:
 - pip install $DJANGO
 - pip install coverage
 - pip install django-allauth
branches:
 only:
  - master
script: coverage run manage.py test pydash
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
